development: &dev
  adapter: postgresql
  database: vuwtabletennis_dev
  username: calebkeene
  password: <%= ENV['PG_DATABASE_PASSWORD'] %>
  host: localhost

production: &production
  <<: *dev
  database: vuwtabletennis_production
  prepared_statements: false